import json,pathlib
root=pathlib.Path(__file__).parent
bank=[]
def add(cat,topic,stem,options,key,explanation,tip='Baca kata kunci pertanyaan sebelum memilih jawaban.'):
 n=len(bank)+1
 bank.append(dict(code=f'CAT{n:03}',category=cat,topic=topic,stem=stem,options=[dict(id=chr(65+i),text=t,score=(key[i] if isinstance(key,list) else 5 if i==key else 0)) for i,t in enumerate(options)],explanation=explanation,tip=tip,source_type='original',review_status='editorial_draft'))
twk=[
('Musyawarah','Kelompok minoritas belum berbicara dalam rapat. Tindakan yang tepat?', ['Mengakhiri rapat','Memberi kesempatan setara sebelum mengambil keputusan','Meminta mereka mengikuti ketua','Menghapus pendapat berbeda','Mengutamakan penyumbang'],1,'Jawaban B memberi semua pihak kesempatan didengar. Musyawarah bukan sekadar menghitung suara; pendapat perlu dipertimbangkan sebelum keputusan dibuat.'),
('Integritas','Anda menerima kelebihan pembayaran perjalanan dinas. Apa tindakan tepat?',['Menyimpan','Membagi kepada tim','Menunggu pemeriksaan','Melaporkan dan mengembalikan melalui prosedur','Memakai tanpa pencatatan'],3,'Uang berlebih bukan hak penerima. Laporkan selisihnya, lalu kembalikan melalui prosedur agar ada bukti pertanggungjawaban.'),
('Nasionalisme','Sikap nasionalisme saat menerima kritik pelayanan pemerintah adalah ...',['Menggunakan kritik berbukti untuk memperbaiki layanan','Menganggap pengkritik tidak cinta negara','Menghapus kritik','Membuka data pribadi pengkritik','Menolak evaluasi'],0,'Kritik yang didukung bukti dapat membantu negara melayani masyarakat lebih baik. Cinta negara juga diwujudkan melalui perbaikan.'),
('Persatuan','Persatuan dalam keberagaman diwujudkan dengan ...',['Menghapus bahasa daerah','Menyeragamkan tradisi','Membatasi pergaulan','Mendahulukan kelompok sendiri','Bekerja sama dan menghormati perbedaan'],4,'Bersatu tidak berarti harus sama. Kita dapat memiliki budaya berbeda sambil bekerja untuk tujuan bersama.'),
('Kemanusiaan','Tindakan sesuai kemanusiaan yang adil dan beradab adalah ...',['Menolong kenalan saja','Mendahulukan kelompok sendiri','Menolong korban berdasarkan kebutuhan tanpa diskriminasi','Mempermalukan korban','Meminta imbalan pertolongan darurat'],2,'Kebutuhan dan keselamatan korban menjadi dasar pertolongan, bukan kedekatan atau asal kelompoknya.'),
('Keadilan','Penerapan keadilan sosial dalam layanan adalah ...',['Menyediakan bantuan akses bagi warga yang menghadapi hambatan','Mendahulukan pemberi hadiah','Menutup layanan daerah terpencil','Biaya berbeda untuk teman','Melayani yang berpakaian rapi saja'],0,'Akses yang adil kadang memerlukan bantuan berbeda. Contohnya, pendampingan formulir untuk warga yang kesulitan membaca.'),
('Toleransi','Fasilitas umum dipakai kelompok berbeda agama. Pengaturan yang tepat?',['Semua jadwal untuk mayoritas','Melarang semuanya','Hanya satu kelompok menentukan','Menyusun kesepakatan jadwal yang adil','Membiarkan perebutan'],3,'Jadwal yang disepakati secara adil membuat hak setiap kelompok dihormati dan mencegah perselisihan.'),
('Bela negara','Contoh bela negara dalam kehidupan sipil adalah ...',['Menyebar kabar belum diperiksa','Menjalankan profesi dengan tanggung jawab','Mengintimidasi warga','Mengabaikan keselamatan','Mengutamakan diri saat darurat'],1,'Bela negara tidak selalu berbentuk kegiatan militer. Pekerjaan yang jujur dan bertanggung jawab ikut menjaga ketahanan masyarakat.'),
('Persatuan','Anda menerima pesan yang menghina suatu suku. Langkah tepat?',['Meneruskan pesan','Menambah hinaan','Membuat tuduhan balasan','Mempercayai langsung','Memeriksa informasi dan tidak menyebar kebencian'],4,'Jangan ikut memperluas provokasi. Periksa sumber dan isi informasi, serta hindari menyebarkan pesan yang merendahkan kelompok.'),
('Pancasila','Pancasila sebagai dasar negara berarti ...',['Hanya untuk upacara','Mengganti semua prosedur','Landasan nilai penyelenggaraan negara','Berlaku hanya bagi aparatur','Tidak terkait kebijakan'],2,'Dasar negara menjadi landasan nilai. Karena itu, penyelenggaraan negara dan kebijakan perlu selaras dengan nilai Pancasila.'),
('Konstitusi','Menurut UUD 1945, kedaulatan berada di tangan ...',['Presiden tanpa batas','Rakyat dan dilaksanakan menurut UUD','Menteri','Partai pemenang sendiri','Mayoritas tanpa aturan'],1,'Pasal 1 ayat (2) menempatkan kedaulatan di tangan rakyat. Pelaksanaannya tetap mengikuti Undang-Undang Dasar.'),
('Konstitusi','Indonesia sebagai negara hukum ditegaskan dalam ...',['Pasal 1 ayat (3)','Pasal 2 ayat (1)','Pasal 3 ayat (1)','Pasal 4 ayat (1)','Pasal 5 ayat (1)'],0,'Pasal 1 ayat (3) UUD 1945 menyatakan bahwa Indonesia adalah negara hukum. Ingat pasangan: ayat 2 kedaulatan, ayat 3 negara hukum.'),
('Pancasila','Persatuan Indonesia adalah sila ...',['Pertama','Kedua','Keempat','Ketiga','Kelima'],3,'Urutan sila ketiga adalah Persatuan Indonesia. Kata persatuan menjadi penanda utamanya.'),
('Kesetaraan','Pelayanan yang menghormati kesamaan kedudukan warga adalah ...',['Menambah syarat bagi orang asing','Mengurangi hak pengkritik','Menerapkan persyaratan sesuai ketentuan tanpa diskriminasi','Mengecualikan kerabat','Menunda berdasarkan asal'],2,'Persyaratan ditentukan aturan layanan, bukan hubungan pribadi, kritik, atau asal daerah pemohon.'),
('Musyawarah','Tujuan musyawarah adalah ...',['Membenarkan pimpinan','Menghilangkan semua perbedaan','Memenangkan mayoritas','Membatasi yang kritis','Mencari keputusan bersama secara bertanggung jawab'],4,'Musyawarah membantu mencari keputusan yang mempertimbangkan kepentingan bersama, bukan sekadar memenangkan satu pihak.'),
('Budaya','Sikap menghargai budaya daerah adalah ...',['Hanya budaya sendiri dilestarikan','Melestarikan budaya lokal dan menghargai budaya lain','Menolak pertukaran','Menertawakan logat','Menghapus adat'],1,'Pelestarian budaya sendiri dapat berjalan bersama penghormatan terhadap budaya orang lain.'),
('Bahasa','Kalimat yang paling efektif adalah ...',['Para peserta-peserta wajib hadir','Kepada peserta agar untuk hadir','Semua para peserta hadir','Peserta wajib hadir tepat waktu','Peserta adalah merupakan pihak yang hadir'],3,'Kalimat D tidak mengulang penanda jamak dan tidak memakai kata mubazir. Isinya jelas: siapa harus melakukan apa.'),
('Bahasa','Manakah kata baku?',['Risiko','Resiko','Ijin','Aktifitas','Analisa'],0,'Bentuk bakunya risiko. Bentuk baku pembanding lainnya ialah izin, aktivitas, dan analisis.'),
('Bahasa','Layanan digital mempercepat pengajuan. Tidak semua warga punya perangkat dan keterampilan. Pendampingan tetap diperlukan. Gagasan utamanya?',['Semua warga sudah mampu','Tatap muka harus dihapus','Dokumen selalu lambat','Perangkat tidak berguna','Digitalisasi perlu disertai pendampingan'],4,'Kalimat-kalimat pendukung menunjukkan kendala akses. Kesimpulannya: digitalisasi tetap membutuhkan pendampingan.'),
('Bahasa','Petugas memeriksa berkas dengan cermat sehingga kesalahan berkurang. Hubungan kalimatnya?',['Pertentangan','Perbandingan','Sebab-akibat','Pilihan','Pengandaian'],2,'Kata sehingga menandai akibat. Sebabnya pemeriksaan cermat; akibatnya kesalahan berkurang.'),
('Keadilan','Pembagian bantuan dengan kebutuhan keluarga berbeda sebaiknya ...',['Untuk teman petugas','Urutan datang saja','Diundi seluruhnya','Menggunakan kriteria kebutuhan transparan','Ditentukan satu penerima'],3,'Kriteria yang terbuka memungkinkan bantuan diberikan sesuai kebutuhan dan hasilnya dapat diperiksa.'),
('Integritas','Anda menilai proposal milik kerabat. Langkah tepat?',['Membantu nilainya','Mengungkap konflik kepentingan dan mengikuti pengunduran diri dari penilaian terkait','Menyembunyikan hubungan','Mengubah kriteria','Memberi nilai rendah tanpa membaca'],1,'Hubungan keluarga dapat memengaruhi atau dianggap memengaruhi penilaian. Ungkapkan hubungan dan gunakan mekanisme penanganan konflik kepentingan.'),
('Gotong royong','Kerja bakti lintas kelompok mencerminkan ...',['Dominasi','Persaingan','Persatuan dan gotong royong','Penghapusan identitas','Pembatasan pendapat'],2,'Warga menyumbangkan tenaga untuk kepentingan bersama meskipun latar belakang mereka berbeda.'),
('Persatuan','Makna Bhinneka Tunggal Ika adalah ...',['Berbeda-beda tetapi tetap satu','Perbedaan dihilangkan','Satu budaya saja','Daerah berdiri sendiri','Bersatu hanya saat ancaman'],0,'Semboyan ini menekankan bahwa keberagaman tetap berada dalam persatuan.'),
('Akuntabilitas','Respons terhadap kritik berbasis data adalah ...',['Menolak pihak luar','Menghapus bukti','Menyerang pengkritik','Menjawab slogan','Menjelaskan fakta dan memperbaiki kekurangan'],4,'Akuntabilitas berarti dapat menjelaskan tindakan dan bertanggung jawab atas perbaikannya.'),
('Demokrasi','Warga menyampaikan aspirasi tertib. Aparatur sebaiknya ...',['Membatasi perbedaan','Mendengar dan menyalurkan melalui mekanisme sesuai','Menganggap ancaman','Menolak pencatatan','Meminta mengganti pendapat'],1,'Aspirasi yang tertib perlu didengar dan ditindaklanjuti melalui saluran yang tepat.'),
('Integritas','Kepentingan pribadi berbenturan dengan tugas. Aparatur harus ...',['Mencari keuntungan','Membebani pemohon','Menunda tanpa kabar','Bertugas objektif dan mengelola konflik kepentingan','Mengubah prosedur untuk diri sendiri'],3,'Pisahkan kepentingan pribadi dari keputusan layanan agar tugas tetap objektif.'),
('Pelayanan','Tujuan aturan antrean adalah ...',['Kekuasaan petugas','Memperlambat','Ketertiban dan perlakuan yang dapat dipertanggungjawabkan','Menolak kelompok','Melarang semua akomodasi'],2,'Antrean mengatur urutan secara jelas. Prioritas yang sah, misalnya kebutuhan aksesibilitas, tetap dapat diakomodasi.'),
('Literasi informasi','Sikap kritis pada informasi publik adalah ...',['Membandingkan sumber dan memeriksa bukti','Percaya yang viral','Memilih judul sensasional','Mengabaikan tanggal','Melihat jumlah pengikut'],0,'Banyak dibagikan belum tentu benar. Periksa sumber, bukti, tanggal, dan konteksnya.'),
('Tanggung jawab','Cara menjaga fasilitas bersama adalah ...',['Memakai tanpa aturan','Membiarkan rusak','Mengutamakan diri','Memindahkan tanpa catatan','Memakai sesuai fungsi dan melaporkan kerusakan'],4,'Pemakaian yang benar memperpanjang manfaat fasilitas; pelaporan membantu kerusakan segera ditangani.')]
for row in twk:add('TWK',*row)
tiu=[
('Analogi','Dokter : pasien = guru : ...',['Sekolah','Buku','Murid','Papan','Kelas'],2,'Dokter melayani pasien. Guru mendidik murid. Hubungannya profesi dengan orang yang dilayani.'),
('Analogi','Kompas : arah = termometer : ...',['Suhu','Udara','Panas','Cuaca','Tekanan'],0,'Kompas menunjukkan arah; termometer mengukur suhu. Pilih hal yang diukur atau ditunjukkan alat.'),
('Verbal','Sinonim cermat adalah ...',['Cepat','Lambat','Ringan','Teliti','Singkat'],3,'Cermat berarti teliti atau saksama. Cepat bukan sinonim karena pekerjaan cepat belum tentu teliti.'),
('Verbal','Antonim stabil adalah ...',['Tetap','Labil','Seimbang','Mantap','Konsisten'],1,'Stabil berarti mantap atau tidak mudah berubah. Lawannya labil, yaitu mudah berubah.'),
('Logika','Semua auditor tim X teliti. Rani auditor tim X. Kesimpulan pasti?',['Semua yang teliti auditor','Rani pemimpin','Hanya Rani auditor','Ada auditor tidak teliti','Rani teliti'],4,'Rani adalah anggota kelompok auditor X. Karena semua anggotanya teliti, Rani juga teliti.'),
('Logika','Jika server utama gagal, sistem beralih ke cadangan. Sistem tidak beralih. Kesimpulan berdasarkan premis?',['Utama lambat','Cadangan rusak','Utama tidak gagal','Keduanya gagal','Tidak ada server'],2,'Aturannya P menyebabkan Q. Ketika Q tidak terjadi, P tidak terjadi menurut premis ini. Pola ini disebut modus tollens.'),
('Logika','Sebagian pegawai adalah peneliti. Semua peneliti tersebut mampu mengolah data. Kesimpulan?',['Sebagian pegawai mampu mengolah data','Semua pegawai peneliti','Semua pengolah data pegawai','Tidak ada pegawai gagal','Semua pegawai mampu'],0,'Pegawai yang menjadi peneliti pasti mampu mengolah data. Kita tidak tahu kemampuan pegawai lainnya.'),
('Logika','Negasi semua berkas telah diverifikasi adalah ...',['Semua belum','Tidak ada yang sudah','Sebagian sudah','Ada berkas yang belum diverifikasi','Selalu diverifikasi'],3,'Cukup satu berkas belum diverifikasi untuk membuat pernyataan semua sudah menjadi salah.'),
('Deret','3, 7, 15, 31, ...',['47','63','62','64','61'],1,'3×2+1=7, 7×2+1=15. Terapkan lagi: 31×2+1=63.'),
('Deret','2, 5, 10, 17, 26, ...',['31','35','36','38','37'],4,'Selisihnya 3,5,7,9. Selisih berikutnya 11 sehingga 26+11=37.'),
('Deret','81, 27, 9, 3, ...',['0','2','1','6','9'],2,'Setiap angka dibagi 3. Maka 3÷3=1.'),
('Deret','A, C, F, J, O, ... (alfabet A–Z)',['U','T','S','V','W'],0,'Posisi huruf 1,3,6,10,15. Tambah 2,3,4,5, lalu 6: posisi 21 adalah U.'),
('Persentase','18% dari 250 adalah ...',['35','40','50','45','55'],3,'18% berarti 18 per 100. Hitung 250×18÷100=45.'),
('Pecahan','3/4 + 2/3 = ...',['5/7','17/12','13/12','7/12','5/12'],1,'Samakan penyebut menjadi 12: 3/4=9/12 dan 2/3=8/12. Jumlahnya 17/12.'),
('Perbandingan','Rasio pria:wanita 3:5. Total 64. Jumlah wanita?',['24','30','32','36','40'],4,'Total bagian 3+5=8. Satu bagian 64÷8=8 orang. Wanita 5×8=40.'),
('Rata-rata','Rata-rata lima nilai 72. Empat nilai berjumlah 280. Nilai kelima?',['70','75','80','85','90'],2,'Jumlah lima nilai 5×72=360. Nilai yang belum diketahui 360−280=80.'),
('Persentase','Harga Rp200.000 didiskon 15%. Harga akhir?',['Rp170.000','Rp175.000','Rp180.000','Rp185.000','Rp190.000'],0,'Diskon 15%×200.000=30.000. Kurangi harga awal: 200.000−30.000=170.000.'),
('Persentase','Rp100.000 naik 20%, lalu turun 20% dari harga baru. Harga akhir?',['Rp80.000','Rp100.000','Rp104.000','Rp96.000','Rp120.000'],3,'Setelah naik menjadi 120.000. Turun 20% dari 120.000 yaitu 24.000. Sisa 96.000, bukan 100.000.'),
('Kerja','6 pekerja selesai 12 hari. Dengan laju sama, 9 pekerja memerlukan ...',['6 hari','8 hari','9 hari','10 hari','18 hari'],1,'Total pekerjaan 6×12=72 orang-hari. Dibagi 9 pekerja menjadi 8 hari.'),
('Kerja','A selesai sendiri 6 jam, B 3 jam. Bersama-sama perlu ...',['1 jam','1,5 jam','3 jam','4,5 jam','2 jam'],4,'Laju per jam A=1/6, B=1/3. Jumlahnya 1/2 pekerjaan per jam. Satu pekerjaan selesai dalam 2 jam.'),
('Kecepatan','150 km ditempuh 2,5 jam. Kecepatan rata-rata?',['50','55','60','65','75'],2,'Kecepatan=jarak÷waktu=150÷2,5=60 km/jam.'),
('Kecepatan','Jarak pergi-pulang sama. Pergi 60 km/jam, pulang 40 km/jam. Rata-rata?',['48','50','45','52','55'],0,'Ambil jarak satu arah 120 km. Waktu pergi 2 jam dan pulang 3 jam. Total 240 km÷5 jam=48 km/jam.'),
('Aljabar','3x−7=20. Nilai x?',['7','8','10','9','11'],3,'Tambah 7 pada kedua sisi: 3x=27. Bagi 3: x=9.'),
('Aljabar','2 buku+3 pena=Rp19.000. 1 buku+1 pena=Rp8.000. Harga buku?',['Rp3.000','Rp5.000','Rp4.000','Rp6.000','Rp7.000'],1,'Kalikan persamaan kedua dengan 2: 2 buku+2 pena=16.000. Selisihnya satu pena=3.000. Buku=8.000−3.000=5.000.'),
('Hitung','√144 + 2³ = ...',['14','16','18','24','20'],4,'Akar 144=12. Pangkat 2³=2×2×2=8. Jumlahnya 20.'),
('Peluang','Peluang angka genap pada satu lemparan dadu seimbang 1–6?',['1/6','1/3','1/2','2/3','5/6'],2,'Angka genap 2,4,6: ada 3 dari 6 kemungkinan. Peluang=3/6=1/2.'),
('Kombinasi','Pilih dua anggota dari lima orang tanpa jabatan. Banyak cara?',['10','20','5','15','25'],0,'Ada 5×4 pasangan berurutan. Karena AB sama dengan BA, bagi 2: 20÷2=10.'),
('Himpunan','Dari 50 peserta, 30 suka matematika, 25 bahasa, 10 keduanya. Tidak suka keduanya?',['0','10','15','5','20'],3,'Yang suka setidaknya satu=30+25−10=45. Kurangi dari total: 50−45=5.'),
('Statistika','Median 4,7,9,10,15 adalah ...',['7','9','10','8','11'],1,'Data sudah urut. Dari lima angka, posisi tengah adalah angka ketiga, yaitu 9.'),
('Persentase','Penjualan naik dari 120 menjadi 150. Kenaikan persentase?',['15%','20%','30%','35%','25%'],4,'Kenaikan 30. Bandingkan dengan nilai awal 120: 30÷120×100%=25%.'),
('Perbandingan','Rasio usia kakak:adik 5:3, jumlah 32 tahun. Selisihnya?',['4','6','8','10','12'],2,'Total 8 bagian=32, jadi satu bagian 4. Selisih 2 bagian=8 tahun.'),
('Skala','Skala 1:250.000, jarak peta 4 cm. Jarak sebenarnya?',['10 km','1 km','5 km','25 km','100 km'],0,'4×250.000=1.000.000 cm. Satu kilometer 100.000 cm, jadi hasilnya 10 km.'),
('Spasial','Panah atas diputar 90° searah jarum jam tiga kali. Arah akhir?',['Atas','Kanan','Bawah','Kiri','Kanan atas'],3,'Putaran pertama kanan, kedua bawah, ketiga kiri. Bayangkan jarum jam bergerak seperempat putaran setiap langkah.'),
('Spasial','Titik (2,1) dicerminkan pada sumbu x=0. Hasil?',['(2,−1)','(−2,1)','(1,2)','(−1,2)','(−2,−1)'],1,'Sumbu x=0 adalah sumbu vertikal. Pencerminan membalik kanan-kiri: x berubah tanda, y tetap.'),
('Urutan','A sebelum B, B sebelum C, D setelah C. Urutan benar?',['B-A-C-D','A-C-B-D','D-A-B-C','A-B-D-C','A-B-C-D'],4,'Gabungkan syarat: A mendahului B, lalu C, lalu D. Maka A-B-C-D.')]
for row in tiu:add('TIU',*row)
# Every scenario carries its own five substantively different options, ordered here by quality then rotated.
cases=[
('Pelayanan','Antrean memanjang karena sistem melambat. Apa tindakan Anda?','Jelaskan gangguan, atur antrean, dan jalankan prosedur cadangan resmi','Jelaskan gangguan dan koordinasikan perbaikan teknis','Bantu warga terdekat tanpa mengatur antrean keseluruhan','Terus bekerja tanpa informasi','Suruh semua warga pulang tanpa solusi','Informasi, ketertiban, dan prosedur cadangan membantu layanan tetap berjalan.'),
('Kerja sama','Rekan kesulitan aplikasi baru; tugas Anda sudah selesai. Anda ...','Bimbing bagian sulit dan pastikan ia bisa melanjutkan sendiri','Kirim panduan dan tawarkan bantuan lanjutan','Tunjukkan satu fitur tanpa mengecek pemahaman','Ambil alih semua tugas tanpa mengajarkan','Suruh mencari bantuan lain','Membimbing lebih bermanfaat daripada terus mengambil alih karena membangun kemandirian.'),
('Integritas','Atasan meminta capaian dinaikkan tanpa bukti. Anda ...','Tolak manipulasi dengan data dan tawarkan laporan perbaikan yang jujur','Minta klarifikasi tertulis sambil mempertahankan data sah','Tolak singkat tanpa tindak lanjut','Tunda laporan tanpa penjelasan','Ubah angka sesuai permintaan','Kejujuran perlu disertai solusi: laporkan keadaan sebenarnya dan rencana perbaikannya.'),
('Pelayanan','Pengguna menyampaikan kritik keras. Anda ...','Dengarkan, periksa masalah, dan tawarkan penyelesaian','Bantu pengguna mengakses jalur pengaduan resmi','Jelaskan prosedur setelah ia selesai berbicara','Pindahkan ke rekan tanpa penjelasan','Balas dengan nada keras','Pahami kebutuhan di balik keluhan sebelum menentukan langkah penyelesaian.'),
('Digital','Dokumen rahasia salah kirim email. Anda ...','Laporkan insiden, batasi dampak melalui jalur resmi, dan catat tindakan','Hubungi penanggung jawab keamanan dan ikuti arahannya','Minta penerima menghapus tetapi tidak melapor internal','Tunggu respons penerima','Hapus dari folder terkirim agar tidak terlihat','Menghapus folder terkirim tidak menarik salinan penerima. Pelaporan cepat memungkinkan mitigasi.'),
('Pelayanan','Warga lansia kesulitan formulir digital. Anda ...','Dampingi sesuai kebutuhan tanpa meminta password atau mengambil persetujuan','Jelaskan langkah dan cek pemahaman lalu bantu','Berikan petunjuk tertulis saja','Isi seluruhnya berdasarkan asumsi','Suruh membawa keluarga','Bantuan harus memudahkan sekaligus menjaga privasi dan kendali pengguna.'),
('Kerja sama','Tim berbeda pendapat tentang metode kerja. Anda ...','Sepakati kriteria, bandingkan bukti, dan putuskan bersama','Dengarkan kedua pihak dan rangkum konsekuensinya','Usulkan voting sebelum membahas konsekuensi','Ikuti yang paling senior saja','Hindari rapat','Kriteria objektif membantu tim memilih berdasarkan kebutuhan, bukan status orang.'),
('Profesionalisme','Dua tugas mendesak memiliki tenggat bertabrakan. Anda ...','Nilai dampak dan konfirmasi prioritas serta jadwal realistis','Susun jadwal dan laporkan risiko terlambat','Minta rekan membantu tanpa penyelarasan prioritas','Kerjakan yang mudah tanpa memberi kabar','Tolak keduanya','Pemberi tugas perlu mengetahui benturan agar prioritas dapat disepakati.'),
('Adaptasi','Anda menemukan metode baru yang mungkin membantu layanan. Anda ...','Periksa relevansi dan usulkan uji terbatas dengan persetujuan','Bahas manfaat dan risiko bersama tim','Bagikan judul artikel saja','Simpan tanpa rencana membaca','Ganti prosedur sendiri','Uji terbatas membantu menilai manfaat dan risiko sebelum diterapkan luas.'),
('Integritas','Teman meminta didahulukan tanpa alasan sah. Anda ...','Jelaskan aturan ramah dan tunjukkan cara layanan sah yang efisien','Jelaskan antrean dan minta mengikuti urutan','Tolak tanpa penjelasan','Suruh datang saat petugas lain','Dahulukan diam-diam','Konsisten pada aturan tidak berarti berhenti membantu; tawarkan jalan yang sah.'),
('Profesionalisme','Laporan Anda yang sudah dikirim ternyata salah. Anda ...','Laporkan dampak, kirim koreksi, dan perbaiki pemeriksaan','Laporkan dan kirim koreksi','Beri tahu rekan tanpa memberi tahu penerima','Ganti file diam-diam','Tunggu sampai ditemukan','Koreksi transparan mencegah keputusan dibuat menggunakan informasi yang salah.'),
('Adaptasi','Pelatihan memakai teknologi yang belum dikuasai. Anda ...','Belajar bertahap, mencoba, dan meminta bantuan spesifik','Baca panduan dan catat pertanyaan','Ikuti sebisanya tanpa bertanya','Minta rekan mengerjakan tugas','Tidak mengikuti','Belajar aktif berarti mencoba dan mengenali bagian yang perlu bantuan.'),
('Sosial budaya','Rekan pendiam memiliki keahlian relevan. Anda ...','Undang pendapatnya dengan ramah tanpa memaksa','Tanya setelah rapat dan sampaikan dengan izinnya','Ingatkan ketua ada anggota belum berpendapat','Paksa menjawab mendadak','Anggap tidak punya ide','Ruang bicara yang aman membantu berbagai karakter berkontribusi.'),
('Integritas','Vendor memberi hadiah selama evaluasi. Anda ...','Tolak dan laporkan sesuai prosedur','Minta arahan penanggung jawab kepatuhan','Tolak tanpa pencatatan','Titipkan hadiah kepada rekan','Terima karena kecil','Hadiah saat evaluasi berisiko memengaruhi objektivitas; penanganannya perlu transparan.'),
('Sosial budaya','Tim berasal dari berbagai daerah. Anda ...','Sepakati cara kerja inklusif dan peran sesuai kompetensi','Gunakan komunikasi yang dipahami bersama','Sopan tetapi menghindari kolaborasi','Minta semua meninggalkan kebiasaan daerah','Hanya bekerja dengan satu daerah','Keberagaman dapat mendukung kerja jika komunikasi dan pembagian perannya adil.'),
('Jejaring','Target tertinggal karena hambatan lintas bagian. Anda ...','Petakan hambatan dan sepakati tindak lanjut serta penanggung jawab','Hubungi bagian terkait untuk mencari jalan keluar','Tambah jam kerja sendiri tanpa menangani hambatan','Tunggu bagian lain bergerak','Salahkan bagian lain di grup','Koordinasi memperjelas siapa melakukan apa dan kapan harus selesai.'),
('Pelayanan','Warga meminta layanan di luar kewenangan unit Anda. Anda ...','Pastikan unit tujuan dan jelaskan langkah serta syarat yang diketahui','Berikan kontak resmi dan sarankan konfirmasi','Sebut unit tujuan tanpa penjelasan','Tebak unit tujuan','Katakan bukan urusan kami','Rujukan yang jelas membantu warga melanjutkan proses tanpa harus menebak.'),
('Sosial budaya','Grup kerja menyebar stereotip agama. Anda ...','Tidak menyebar, ingatkan proporsional, dan laporkan jika serius/berulang','Ingatkan pengirim secara pribadi','Alihkan percakapan tanpa membahas masalah','Keluar tanpa tindakan','Tambahkan candaan serupa','Pilih respons proporsional yang mencegah diskriminasi dan menjaga keselamatan hubungan kerja.'),
('Digital','Aplikasi resmi rusak; ada tawaran aplikasi tak dikenal untuk data warga. Anda ...','Periksa izin dan keamanan melalui pihak berwenang sebelum memakai','Laporkan gangguan dan minta prosedur cadangan','Hentikan pekerjaan tanpa koordinasi','Coba sebagian data warga','Unggah semua data','Data warga tidak boleh dijadikan bahan percobaan pada layanan yang belum disetujui.'),
('Adaptasi','Proses berulang menghabiskan waktu. Anda ...','Ukur hambatan, usulkan perbaikan, dan uji dampak bersama','Catat langkah boros dan usulkan perbaikan','Sampaikan keluhan umum','Ubah sendiri tanpa memberi tahu','Abaikan karena kebiasaan','Pengukuran memberi dasar untuk menentukan apakah perubahan benar-benar membantu.'),
('Kerja sama','Rekan baru berulang membuat kesalahan ringan. Anda ...','Beri umpan balik pribadi yang spesifik, dampingi, dan cek perbaikan','Jelaskan kesalahan dengan contoh benar','Kirim panduan tanpa diskusi','Ambil alih pekerjaannya terus','Tegur di depan pengguna','Umpan balik perlu menunjukkan apa yang diperbaiki dan bagaimana caranya.'),
('Profesionalisme','Data yang diminta belum selesai diverifikasi. Anda ...','Jelaskan status, berikan data valid, dan sepakati waktu pembaruan','Minta waktu tambahan untuk verifikasi','Beri perkiraan tanpa label','Tolak menjawab tanpa penjelasan','Sajikan sebagai data final','Pisahkan yang sudah pasti dari yang belum diperiksa agar penerima tidak salah menafsirkan.'),
('Sosial budaya','Rapat sulit diakses salah satu anggota karena kebutuhan aksesibilitas. Anda ...','Bahas penyesuaian agar semua dapat berpartisipasi efektif','Sediakan alternatif partisipasi yang dapat diakses','Kirim ringkasan setelah rapat','Minta menerima hasil tanpa ikut','Abaikan karena hanya satu orang','Partisipasi berarti dapat menyampaikan pendapat, bukan hanya menerima keputusan akhir.'),
('Digital','Rekan meminta password akun kerja untuk bergantian tugas. Anda ...','Tolak berbagi password dan usulkan akses individual','Jelaskan risiko dan hubungi admin sistem','Bagikan lalu ganti password','Kirim lewat pesan pribadi','Bagikan di grup','Akun individual menjaga keamanan sekaligus mencatat siapa melakukan suatu tindakan.'),
('Pelayanan','Janji penyelesaian layanan sebelumnya tidak terpenuhi. Anda ...','Periksa status, akui kendala, sepakati tindak lanjut dan beri pembaruan','Minta maaf dan beri estimasi setelah memeriksa','Minta menunggu tanpa kepastian','Salahkan petugas sebelumnya','Hindari pengguna','Kepercayaan pulih melalui informasi nyata dan tindak lanjut yang bisa dipantau.'),
('Profesionalisme','Instruksi lisan tampak bertentangan dengan prosedur tertulis. Anda ...','Klarifikasi kepada pihak berwenang dan dokumentasikan keputusan sah','Tunjukkan perbedaan kepada atasan dan minta penegasan','Tunda bagian terkait sambil membaca prosedur','Ikuti lisan tanpa memeriksa','Pilih yang menguntungkan diri','Konflik instruksi harus diselesaikan berdasarkan kewenangan, bukan tebakan.'),
('Kerja sama','Rekan mengusulkan ide berbeda dari ide Anda. Anda ...','Bandingkan bukti dan kebutuhan, lalu dukung solusi terbaik','Minta masukan tim pada kedua ide','Dengarkan tetapi tetap pilih sendiri tanpa evaluasi','Tolak agar cepat','Cari cela untuk menjatuhkan','Tujuan tim adalah hasil terbaik, bukan mempertahankan kepemilikan ide.'),
('Jejaring','Tugas Anda selesai sementara tim lain kewalahan dalam bidang yang Anda kuasai. Anda ...','Tawarkan bantuan terkoordinasi sambil menjaga tanggung jawab sendiri','Tanyakan prioritas bantuan ke koordinator','Berikan tips singkat saja','Ambil alih pekerjaan tanpa izin','Pulang tanpa mengecek kebutuhan','Bantuan yang dikoordinasikan mencegah pekerjaan ganda dan pembagian tanggung jawab yang kabur.'),
('Digital','Email mengaku dari admin tetapi domain login berbeda. Anda ...','Jangan masukkan kredensial; verifikasi kanal resmi dan laporkan','Hubungi admin resmi untuk konfirmasi','Hapus tanpa melapor','Teruskan agar rekan mencoba','Masukkan password untuk mengecek','Tautan palsu dapat mencuri password. Gunakan kanal resmi yang sudah dikenal.'),
('Pelayanan','Program baru kurang diminati warga. Anda ...','Periksa kebutuhan dan hambatan akses lalu uji perbaikan terukur','Kumpulkan umpan balik dan perbaiki masalah utama','Tanya beberapa orang secara informal','Tambah promosi tanpa mencari penyebab','Salahkan warga','Minat rendah bisa disebabkan kebutuhan tidak cocok atau akses sulit, bukan semata kurang promosi.'),
('Sosial budaya','Ada usulan membedakan layanan berdasarkan suku. Anda ...','Tolak dasar diskriminatif dan arahkan ke kriteria objektif','Jelaskan pentingnya perlakuan setara','Minta ditunda tanpa alasan','Diam meskipun tidak setuju','Setujui demi kekompakan','Keputusan layanan harus menggunakan kebutuhan dan aturan yang relevan, bukan identitas suku.'),
('Adaptasi','Tugas baru tetap sulit setelah membaca panduan. Anda ...','Rumuskan kendala spesifik, coba langkah aman, lalu minta arahan','Pelajari contoh pekerjaan sejenis','Ulangi cara sama terus','Serahkan semua ke rekan','Sembunyikan sampai tenggat','Pertanyaan spesifik memudahkan orang lain membantu dan mempercepat pembelajaran.'),
('Sosial budaya','Rekan bercerita diperlakukan tidak adil. Anda ...','Dengarkan tanpa menghakimi dan bantu memahami jalur dukungan','Sarankan konsultasi pihak tepat sambil menjaga rahasia','Sampaikan simpati tanpa menanyakan kebutuhan','Sebarkan cerita agar ramai','Anggap terlalu sensitif','Dukungan yang aman menghormati kerahasiaan dan pilihan rekan.'),
('Profesionalisme','Dua sumber laporan menunjukkan angka berbeda. Anda ...','Telusuri definisi, periode, dan sumber sebelum menetapkan angka','Hubungi pemilik data untuk klarifikasi','Tunda laporan tanpa penjelasan','Ambil rata-rata tanpa dasar','Pilih angka lebih tinggi','Perbedaan definisi atau periode dapat menghasilkan angka berbeda meski tidak ada salah hitung.'),
('Kerja sama','Anda mempresentasikan keberhasilan tim. Anda ...','Sajikan data, akui kontribusi tim, dan jelaskan pembelajaran','Jelaskan hasil dan apresiasi anggota','Sebut tim secara umum','Tidak menyebut kontribusi lain','Akui seluruh pekerjaan sebagai milik sendiri','Hasil yang dapat dipertanggungjawabkan mencakup bukti, kontribusi, dan pelajaran.'),
('Pelayanan','Seorang pengguna tunarungu datang tanpa pendamping. Anda ...','Tanyakan cara komunikasi yang nyaman dan sediakan bantuan aksesibel','Gunakan tulisan sederhana dan cek pemahaman','Berikan formulir tanpa penjelasan','Suruh kembali dengan pendamping','Tolak layanan','Tanyakan kebutuhan orang tersebut, bukan berasumsi ia tidak mampu mengurus layanan.'),
('Integritas','Data absensi Anda tercatat hadir padahal izin. Anda ...','Laporkan dan minta koreksi sesuai bukti izin','Hubungi petugas absensi untuk klarifikasi','Tunggu rekap sebelum bertanya','Biarkan karena izin sah','Manfaatkan untuk klaim tambahan','Izin sah tetap perlu dicatat sesuai keadaan sebenarnya; akurasi administrasi penting.'),
('Adaptasi','Hasil uji inovasi tidak sebaik perkiraan. Anda ...','Analisis penyebab bersama dan putuskan perbaikan atau penghentian berdasar data','Laporkan hasil dan usulkan evaluasi','Coba lagi tanpa perubahan','Tunda laporan kegagalan','Ubah data agar terlihat berhasil','Uji yang kurang berhasil tetap memberi informasi; jangan menutupi hasilnya.'),
('Jejaring','Bagian lain belum mengirim data yang diperlukan. Anda ...','Konfirmasi hambatan, sepakati tenggat realistis dan alternatif data sah','Kirim pengingat dan tawarkan bantuan','Kirim pengingat umum','Menunggu tanpa kabar','Membuat data sendiri','Koordinasi aktif mencari solusi tanpa mengorbankan keabsahan data.'),
('Digital','Anda hendak mengunggah laporan internal ke alat AI umum. Anda ...','Periksa klasifikasi data dan izin, gunakan hanya data yang disetujui','Konsultasikan kepada penanggung jawab sebelum memakai','Hapus nama tetapi belum memeriksa sensitivitas lain','Unggah sebagian untuk mencoba','Unggah seluruh laporan','Menghapus nama belum tentu menghilangkan data sensitif; aturan penggunaan tetap harus diperiksa.'),
('Profesionalisme','Rekan meminta Anda menyetujui dokumen yang belum dibaca. Anda ...','Periksa bagian yang menjadi tanggung jawab sebelum menyetujui','Minta waktu yang diperlukan untuk membaca','Baca judul saja','Setujui karena percaya rekan','Berikan akun agar ia menyetujui sendiri','Persetujuan membawa tanggung jawab. Kepercayaan tidak menggantikan pemeriksaan.'),
('Pelayanan','Warga mengeluhkan persyaratan yang berbeda antarpelayanan. Anda ...','Periksa aturan terbaru, luruskan informasi, dan koordinasikan konsistensi','Cek aturan lalu jelaskan yang berlaku','Tunjukkan daftar di meja tanpa memeriksa','Minta mengikuti yang paling banyak','Menambahkan syarat agar aman','Kepastian persyaratan mengurangi beban warga dan mencegah keputusan sewenang-wenang.'),
('Kerja sama','Anda akan cuti saat pekerjaan tim masih berjalan. Anda ...','Siapkan serah terima status, dokumen, dan penanggung jawab bersama','Berikan catatan pekerjaan kepada koordinator','Kirim pesan umum bahwa sedang cuti','Tinggalkan berkas tanpa penjelasan','Tidak memberi kabar','Serah terima yang jelas menjaga kelanjutan pekerjaan saat anggota tidak hadir.'),
('Sosial budaya','Jadwal kegiatan tim bertepatan dengan ibadah sebagian anggota. Anda ...','Diskusikan penyesuaian adil tanpa menghambat tujuan kegiatan','Cari waktu alternatif bersama koordinator','Izinkan absen tanpa menyediakan informasi pengganti','Minta mereka memilih kerja atau ibadah','Mengolok kebutuhan mereka','Penyesuaian yang dibahas bersama menjaga partisipasi dan penghormatan keyakinan.'),
('Integritas','Anda menemukan kuitansi yang tidak cocok dengan transaksi. Anda ...','Verifikasi bukti, laporkan ketidaksesuaian melalui jalur tepat, dan koreksi','Minta klarifikasi penanggung jawab transaksi','Tunda pemrosesan tanpa penjelasan','Ganti angka agar cocok','Proses saja agar cepat','Ketidakcocokan harus diverifikasi, bukan disesuaikan secara fiktif.')]
for i,c in enumerate(cases):
 topic,stem,*rest=c
 opts=rest[:5]; reason=rest[5]
 # deterministic rotation; scores attached to option identity
 shift=(i*3+1)%5
 paired=list(zip(opts,[5,4,3,2,1]));paired=paired[shift:]+paired[:shift]
 add('TKP',topic,stem,[p[0] for p in paired],[p[1] for p in paired],reason,'Cari tindakan yang membantu, sesuai aturan, dan memiliki tindak lanjut. Bobot ini adalah penilaian latihan, bukan kunci resmi BKN.')
 for o in bank[-1]['options']:
  o['reason']=f"Bobot {o['score']}/5. "+{5:'Pilihan paling lengkap untuk kebutuhan kasus ini. '+reason,4:'Arah tindakan sudah tepat, tetapi tindak lanjutnya belum selengkap pilihan berbobot 5.',3:'Ada upaya membantu, tetapi belum menyelesaikan masalah utama secara memadai.',2:'Tindakan ini berisiko menunda penyelesaian atau mengabaikan tanggung jawab penting.',1:'Pilihan ini paling lemah karena mengabaikan kebutuhan, integritas, atau keselamatan dalam kasus ini.'}[o['score']]
assert len(bank)==110,len(bank)
(root/'bank-soal.json').write_text(json.dumps(bank,ensure_ascii=False,indent=2))
def sqlstr(x):return "'"+x.replace("'","''")+"'"
lines=['begin;']
for q in bank:lines.append('insert into cat_private.questions(code,payload) values ('+sqlstr(q['code'])+','+sqlstr(json.dumps(q,ensure_ascii=False))+'::jsonb) on conflict(code) do nothing;')
for id,title,mode,codes,official in [('latihan-100','Latihan lengkap · 100 soal','learn',bank[:100],False),('simulasi-110','Simulasi SKD · 110 soal','exam',bank,True),('twk-30','Fokus TWK · Kebangsaan','learn',bank[:30],False),('tiu-35','Fokus TIU · Logika & hitungan','learn',bank[30:65],False),('tkp-45','Fokus TKP · Situasi kerja','learn',bank[65:],False)]:
 lines.append('insert into cat_private.packages values ('+','.join([sqlstr(id),sqlstr(title),sqlstr(mode),'6000',"ARRAY["+','.join(sqlstr(q['code']) for q in codes)+"]",'true',str(official).lower()])+') on conflict(id) do nothing;')
lines.append('commit;');(root/'02-seed.sql').write_text('\n'.join(lines))
print('Bank:',len(bank),'soal; 30 TWK, 35 TIU, 45 TKP')
