// @vitest-environment jsdom
import{afterEach,describe,it,expect}from'vitest';import{render,screen,cleanup,fireEvent}from'@testing-library/react';import App from'../src/App';
afterEach(cleanup);
describe('Learner walkthrough',()=>{
 it('shows honest public dashboard and no invented progress',()=>{render(<App/>);expect(screen.getByText('Selangkah lebih siap.')).toBeTruthy();expect(screen.getByText('Mulai sesi pertama Anda')).toBeTruthy();expect(screen.getAllByText(/Bukan aplikasi resmi BKN/).length).toBeGreaterThan(0);});
 it('checks a wrong answer, explains discount step by step, locks choice',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Coba latihan gratis/}));const check=screen.getByRole('button',{name:/Periksa jawaban/})as HTMLButtonElement;expect(check.disabled).toBe(true);fireEvent.click(screen.getByRole('radio',{name:/A Rp20.000/}));fireEvent.click(check);expect(screen.getByText(/Langkah 1: cari potongan/)).toBeTruthy();expect(screen.getByText(/Belum tepat/)).toBeTruthy();expect((screen.getAllByRole('radio')[0]as HTMLInputElement).disabled).toBe(true);});
 it('moves through all three demo items and reveals TKP weights',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Coba latihan gratis/}));for(let i=0;i<3;i++){fireEvent.click(screen.getAllByRole('radio')[i]);fireEvent.click(screen.getByRole('button',{name:/Periksa jawaban/}));if(i<2)fireEvent.click(screen.getByRole('button',{name:/Soal berikutnya/}));}expect(screen.getByText(/Bobot pilihan Anda: 5\/5/)).toBeTruthy();fireEvent.click(screen.getByText('Lihat bobot dan alasan setiap pilihan'));expect(screen.getByText('C · 5/5')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Pilih paket belajar/}));expect(screen.getByText('Selangkah lebih siap.')).toBeTruthy();});
 it('gates actual session behind login',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Mulai simulasi'}));expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.getByText(/Pendaftaran tahap uji dikelola admin/)).toBeTruthy();});
});
