// @vitest-environment jsdom
import{afterEach,describe,it,expect}from'vitest';import React from'react';import{render,screen,cleanup,fireEvent}from'@testing-library/react';import App from'../src/App';
afterEach(cleanup);
describe('Learner walkthrough',()=>{
 it('shows honest public dashboard and no invented progress',()=>{render(<App/>);expect(screen.getByText('Selangkah lebih siap.')).toBeTruthy();expect(screen.getByText('Mulai sesi pertama Anda')).toBeTruthy();expect(screen.getAllByText(/Bukan aplikasi resmi BKN/).length).toBeGreaterThan(0);});
 it('checks a wrong answer, explains discount step by step, locks choice',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Coba latihan gratis/}));const check=screen.getByRole('button',{name:/Periksa jawaban/})as HTMLButtonElement;expect(check.disabled).toBe(true);fireEvent.click(screen.getByRole('radio',{name:/A Rp20.000/}));fireEvent.click(check);expect(screen.getByText(/Langkah 1: cari potongan/)).toBeTruthy();expect(screen.getByText(/Belum tepat/)).toBeTruthy();expect((screen.getAllByRole('radio')[0]as HTMLInputElement).disabled).toBe(true);});
 it('moves through all three demo items and reveals TKP weights',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/Coba latihan gratis/}));for(let i=0;i<3;i++){fireEvent.click(screen.getAllByRole('radio')[i]);fireEvent.click(screen.getByRole('button',{name:/Periksa jawaban/}));if(i<2)fireEvent.click(screen.getByRole('button',{name:/Soal berikutnya/}));}expect(screen.getByText(/Bobot pilihan Anda: 5\/5/)).toBeTruthy();fireEvent.click(screen.getByText('Lihat bobot dan alasan setiap pilihan'));expect(screen.getByText('C · 5/5')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Pilih paket belajar/}));expect(screen.getByText('Selangkah lebih siap.')).toBeTruthy();});
 it('gates actual session behind login',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Mulai simulasi'}));expect(screen.getByRole('dialog')).toBeTruthy();expect(screen.getByText(/Pendaftaran tahap uji dikelola admin/)).toBeTruthy();});
});
describe('Kerapian UI dan aksesibilitas',()=>{
 it('render di StrictMode tanpa error konsol di luar peringatan act',()=>{const errors:string[]=[];const original=console.error;console.error=(...args:unknown[])=>{errors.push(String(args[0]));};try{render(<React.StrictMode><App/></React.StrictMode>);}finally{console.error=original;}expect(screen.getByText('Selangkah lebih siap.')).toBeTruthy();expect(screen.getByText('110')).toBeTruthy();expect(errors.filter(e=>!/not wrapped in act/i.test(e))).toEqual([]);});
 it('menu mobile punya nama aksesibel dan membuka sidebar',()=>{render(<App/>);const toggle=screen.getByRole('button',{name:'Buka menu'});const sidebar=document.querySelector('.sidebar')as HTMLElement;expect(sidebar).toBeTruthy();expect(sidebar.classList.contains('open')).toBe(false);fireEvent.click(toggle);expect(sidebar.classList.contains('open')).toBe(true);});
 it('sidebar auto-hidden: scrim menutup drawer dan aria-expanded ikut berubah',()=>{render(<App/>);const toggle=screen.getByRole('button',{name:'Buka menu'});expect(toggle.getAttribute('aria-expanded')).toBe('false');expect(toggle.getAttribute('aria-controls')).toBe('app-sidebar');fireEvent.click(toggle);expect(toggle.getAttribute('aria-expanded')).toBe('true');const scrim=document.querySelector('.scrim')as HTMLElement;expect(scrim).toBeTruthy();fireEvent.click(scrim);expect(document.querySelector('.sidebar')as HTMLElement).toBeTruthy();expect((document.querySelector('.sidebar')as HTMLElement).classList.contains('open')).toBe(false);expect(document.querySelector('.scrim')).toBeNull();});
 it('Escape dan tombol tutup panel menutup sidebar',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Buka menu'}));fireEvent.keyDown(window,{key:'Escape'});expect((document.querySelector('.sidebar')as HTMLElement).classList.contains('open')).toBe(false);fireEvent.click(document.querySelector('.mobile-menu')as HTMLElement);expect((document.querySelector('.sidebar')as HTMLElement).classList.contains('open')).toBe(true);fireEvent.click(document.querySelector('.nav-close')as HTMLElement);expect((document.querySelector('.sidebar')as HTMLElement).classList.contains('open')).toBe(false);});
 it('menyediakan tautan lewati ke konten utama',()=>{render(<App/>);const skip=screen.getByRole('link',{name:/Lewati ke konten/})as HTMLAnchorElement;expect(skip.getAttribute('href')).toBe('#konten-utama');expect(document.querySelector('main#konten-utama')).toBeTruthy();});
 it('modal login aksesibel dan fokus berpindah ke dalam dialog',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/^Masuk/}));const dialog=screen.getByRole('dialog');expect(dialog.getAttribute('aria-modal')).toBe('true');expect(dialog.getAttribute('aria-labelledby')).toBe('login-title');expect(dialog.contains(document.activeElement)).toBe(true);});
 it('tanpa konfigurasi Supabase tetap menampilkan pemberitahuan yang jujur',()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:/^Masuk/}));expect(screen.getByText(/Koneksi belum dikonfigurasi/)).toBeTruthy();const submit=screen.getByRole('button',{name:/Masuk ke ruang belajar/})as HTMLButtonElement;expect(submit.disabled).toBe(true);});
});
